name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - patch-2
    tags: 
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
    
      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
    
      - name: "publish firefox"
        uses: trmcnvn/firefox-addon@v1
        continue-on-error: true
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: '{afa62fd6-94ef-471f-b3d7-655451b263bf}'
          xpi:  ${{ steps.web-ext-build.outputs.target }}
          manifest: src/manifest.json
          api-key: ${{ secrets.AMO_SIGN_KEY }}
          api-secret: ${{ secrets.AMO_SIGN_SECRET }}
          
      - name: "upload firefox build as artifact"
        uses: actions/upload-artifact@master
        continue-on-error: true
        with:
          name: userstyle
          path: ${{ steps.web-ext-build.outputs.target }} 
          
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r src.zip src
          
      - name: "upload zip"
        uses: actions/upload-artifact@master
        with:
          name: src
          path: src.zip 
      
      - name: "publish chrome"
        continue-on-error: true
        uses: trmcnvn/chrome-addon@v2
        with:
          # extension is only necessary when updating an existing addon,
          # omitting it will create a new addon
          extension: jfcdlkkkngaallphcckjjbnokjonloan
          zip: src.zip
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.CLIENT_REFRESH }}
          # optionally specify the visibility of the addon
          publishTarget: default
